version: 0.1.0.{build}
os: Visual Studio 2017
branches:
  only:
    - master
install:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -outfile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
build_script:
  - ps: .\scripts\build.ps1 -IsOfficialBuild
after_build:
  - ps: .\scripts\package.ps1 -IsOfficialBuild
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
  - path: 'artifacts\*.zip'
    name: Binaries
deploy:
  release: nyancat-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
# deploy:
#   - provider: NuGet
#     name: myget
#     artifact: Packages
#     api_key:
#       secure: adddhere