version: 0.1.0.{build}
os: Visual Studio 2017
branches:
  only:
    - master
install:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -outfile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
build_script:
  - ps: .\build.ps1 -IsOfficialBuild
after_build:
  - ps: 7z a "artifacts/nyancat-winx64-$APPVEYOR_BUILD_VERSION.zip" .build/bin/Release/netcoreapp2.1/win-x64/publish
  - ps: 7z a "artifacts/nyancat-linux-$APPVEYOR_BUILD_VERSION.zip" .build/bin/Release/netcoreapp2.1/linux-x64/publish
  - ps: 7z a "artifacts/nyancat-osx-$APPVEYOR_BUILD_VERSION.zip" .build/bin/Release/netcoreapp2.1/osx-x64/publish
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
  - path: 'articats\*.zip'
    name: Binaries
deploy:
  release: nyancat-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
# deploy:
#   - provider: NuGet
#     name: myget
#     artifact: Packages
#     api_key:
#       secure: adddhere