name: PR Workflow

on: [pull_request]

jobs:
  test_pr:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.301'
    - run: make
